version: "3.4"

services:
  # Kafka local
  upstash_kafka:
    build:
      context: .
    container_name: upstash_kafka_local
    hostname: upstash-kafka-local
    depends_on:
      - kafka
    ports:
      - 3000:8080
    environment:
      - PORT=8080
      - KAFKA_URL=kafka://kafka:9092
  # Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.4.0
    hostname: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
